### ISSUE TITLE
Unable to detect 2022 SR/F

### ISSUE THREAD

**Issue by codecivet** [Belkaar/ZeroNavBridge#2]
I followed the pairing instructions:

- SR/F is successfully paired with the Zero Next Gen app. Confirmed the bike has the BT icon and the app is working.
- Killed the Zero Next Gen app and confirmed the BT icon is gone from the bike dash.
- Start Zero Bridge
- Permissions have been granted
- Enabled Nav Bridge and Google Maps notifications
- Turn on bike
- Get repeated `scan failed 5` debug messages

LMK if there is any info I can provide.

**Comment by Belkaar** [comment]
I seem to have found a possible cause and solution to this here:

https://stackoverflow.com/questions/51102089/android-bluetooth-le-scan-failed-out-of-hardware-resources

I'll look into making the change suggested there.

In the mean time the article suggests turning bluetooth on your phone off and on again if scan error 5 happens.

**Comment by codecivet** [comment]
Thanks for the tip. Turn BT off/on didn't work, but what did work was turning on airplane mode, then going to the Nav Bridge app, which would request to turn BT on. When I "allow"ed it to turn on BT, it detected my bike!

**Comment by Belkaar** [comment]
Should be resolved in Release 1.4. Please report any further issues
